package az.texnoera.bank.common.api;

public enum ErrorCode {
    VALIDATION_ERROR,

    NOT_FOUND,
    USER_NOT_FOUND,
    ACCOUNT_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    COMPLAINT_NOT_FOUND,

    BAD_REQUEST,

    EMAIL_ALREADY_EXISTS,
    FIN_ALREADY_EXISTS,

    INTERNAL_SERVER_ERROR,

    INVALID_PASSWORD,
    INVALID_REQUEST,

    INVALID_EMAIL_VERIFICATION_TOKEN,
    EMAIL_VERIFICATION_TOKEN_EXPIRED,

    UNAUTHORIZED,
    SERVICE_UNAVAILABLE,
    FORBIDDEN
}
