package az.texnoera.bank.common.api;

public enum ErrorCode {
    VALIDATION_ERROR,

    USER_NOT_FOUND,

    EMAIL_ALREADY_EXISTS,
    FIN_ALREADY_EXISTS,

    INTERNAL_SERVER_ERROR,

    INVALID_PASSWORD,
    INVALID_REQUEST,

    INVALID_EMAIL_VERIFICATION_TOKEN,
    EMAIL_VERIFICATION_TOKEN_EXPIRED,

    UNAUTHORIZED,
    FORBIDDEN
}
